version: '3'

volumes:
  postgres:

services:
  app:
    container_name: hipstu_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: hipstu
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=hipstu.settings
      - LOCAL_SETTINGS_MODULE=settings.docker
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=boi
      - POSTGRES_USER=boi
      - POSTGRES_PASSWORD=pw
      - DEBUG=True
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app/hipstu_backend
    ports:
      - 8000:8000
    networks:
      app:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: boi
      POSTGRES_PASSWORD: pw
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      app:

networks:
  app:
