# Generated by Django 2.1 on 2019-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='affiliate_url_added_by',
        ),
        migrations.AlterField(
            model_name='link',
            name='affiliate_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
